# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    """ Say hellow to someone.

    param: to: string
    """
    return f'Hello, {to}'